[build]
target = "node"
outdir = "dist"
sourcemap = "inline"

[build.commonjs]
format = "cjs"

[build.paths]
"@/*" = "./src/*"
"@commands/*" = "./src/commands/*"
"@core/*" = "./src/core/*"
"@types/*" = "./src/types/*"
"@actions/*" = "./src/actions/*"