[build]
target = "node"
outdir = "dist"
sourcemap = "inline"

[build.commonjs]
format = "cjs"

[build.paths]
"@/*" = "./src/*"
"@commands/*" = "./src/commands/*"
"@core/*" = "./src/core/*"
"@infrastructure/*" = "./src/infrastructure/*"
"@services/*" = "./src/services/*"